<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.estore.eval.estore</groupId>
    <artifactId>ldbc</artifactId>
    <version>1.0.0</version>
  </parent>
  <groupId>org.estore.eval.estore.ldbc</groupId>
  <artifactId>finbench</artifactId>
  <name>Estore FinBench Evaluation</name>
  <description>Estore implementation for the LDBC FinBench driver</description>
  <dependencies>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-csv</artifactId>
      <version>1.10.0</version>
    </dependency>
      <dependency>
        <groupId>org.neo4j.driver</groupId>
        <artifactId>neo4j-java-driver</artifactId>
        <version>4.3.3</version><!-- 4.3.3 -->
      </dependency>
      <dependency>
        <groupId>com.arcadedb</groupId>
        <artifactId>arcadedb-engine</artifactId>
        <version>24.1.1</version>
        <scope>system</scope>
        <systemPath>/home/libs/arcadedb-engine-24.1.1.jar</systemPath>
      </dependency>
      <dependency>
        <groupId>com.arcadedb</groupId>
        <artifactId>arcadedb-gremlin</artifactId>
        <version>24.1.1</version>
        <scope>system</scope>
        <systemPath>/home/libs/arcadedb-gremlin-24.1.1.jar</systemPath>
      </dependency>
      <dependency>
        <groupId>org.apache.tinkerpop</groupId>
        <artifactId>gremlin-shaded</artifactId>
        <version>3.7.1</version>                                                                                      
      </dependency>
      <dependency>
        <groupId>org.apache.tinkerpop</groupId>
        <artifactId>gremlin-server</artifactId>
        <version>3.7.1</version>
      </dependency>
      <dependency>
        <groupId>org.apache.tinkerpop</groupId>
        <artifactId>gremlin-language</artifactId>
        <version>3.7.1</version>
      </dependency>
      <dependency>
        <groupId>org.antlr</groupId>
        <artifactId>antlr4-runtime</artifactId>
        <version>4.9.1</version>
      </dependency>
      <dependency>
        <groupId>org.apache.tinkerpop</groupId>
        <artifactId>gremlin-driver</artifactId>
        <version>3.7.1</version>                                                                                      
      </dependency>
      <dependency>
        <groupId>org.apache.tinkerpop</groupId>
        <artifactId>gremlin-util</artifactId>
        <version>3.7.1</version>
      </dependency>
      <dependency>
        <groupId>org.apache.tinkerpop</groupId>
        <artifactId>gremlin-groovy</artifactId>
        <version>3.7.1</version>
        <exclusions>
          <exclusion>
            <groupId>jline</groupId>
            <artifactId>jline</artifactId>
          </exclusion>
        </exclusions>
      </dependency>
      <dependency>
        <groupId>org.apache.tinkerpop</groupId>
        <artifactId>gremlin-core</artifactId>
        <version>3.7.1</version>
        <scope>system</scope>
        <systemPath>/home/libs/gremlin-core-3.7.1.jar</systemPath>
      </dependency>
      <dependency>
        <groupId>com.arcadedb</groupId>
        <artifactId>arcadedb-network</artifactId>
        <version>24.1.1</version>
        <scope>system</scope>
        <systemPath>/home/libs/arcadedb-network-24.1.1.jar</systemPath>
      </dependency>
      <dependency>
        <groupId>com.google.code.gson</groupId>
        <artifactId>gson</artifactId>
        <version>2.10.1</version>
      </dependency>   
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.4.1</version>
        <configuration>
          <!-- put your configurations here -->
        </configuration>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
